### ISSUE TITLE
Adding Contributor section in readme ( Automatically )

### ISSUE THREAD

**Issue by sahilempire** [PoojaMittal2842/Delhi-Tourism#105]
I will like to add a feature this will **update contributor list in README.md automatically** !! Will start to work on this **issue as soon as I get assigned** !

Thank You

**Comment by rohank2502** [comment]
> 
> 
> I will like to add a feature this will **update contributor list in README.md automatically** !! Will start to work on this **issue as soon as I get assigned** !
> 
> Thank You

Copy #64
