### ISSUE TITLE
Design Issue: Change the hover effect of places cards on home page

### ISSUE THREAD

**Issue by mis-coder** [PoojaMittal2842/Delhi-Tourism#134]
When we hover those places cards on the homepage, the images are translated upwards due to which other content is hidden, which I think is not a good way of styling.

So I would like to change the hover effect of those cards to an overlay. Basically when someone will hover on any of the cards, the content will appear as an overlay.

This is an example, of what I want to do:
![image-hover](https://user-images.githubusercontent.com/51118723/111894864-52fa4d00-8a34-11eb-83e7-dd7850d5810f.gif)

Please assign this issue to me so that I can contribute in making this website a better experience for the users

**Comment by maverick1910** [comment]
@mis-coder go ahead, please try to submit it within 4 days

**Comment by mis-coder** [comment]
> @mis-coder go ahead, please try to submit it within 4 days

Sure, and please assign it to me as you haven't yet. Though I have started working on it already.
