### ISSUE TITLE
Adding a preloader

### ISSUE THREAD

**Issue by padmajabhol** [PoojaMittal2842/Delhi-Tourism#17]
I want to add a theme based preloader to this site.

**Comment by Vijay-Git03** [comment]
I want to add preloader for this website @PoojaMittal2842

**Comment by PoojaMittal2842** [comment]
@padmajabhol After adding preloader upload a short video showing the changes.

**Comment by padmajabhol** [comment]
> @padmajabhol After adding preloader upload a short video showing the changes.



https://user-images.githubusercontent.com/75530516/111021214-d8587e80-83f0-11eb-8591-50a7ce9fb264.mp4

Is this okay? Should I send the PR?
