### ISSUE TITLE
Registration section of the home page

### ISSUE THREAD

**Issue by prisha-srivastava** [PoojaMittal2842/Delhi-Tourism#18]
I would like to improve the registration section of the homepage by changing the background and styling. Contributing as a participant of GSSOC'21. Could you please assign it to me?

**Comment by Riya764** [comment]
I would like to work on this issue.Please assign this to me as a part of GSSOC'21

**Comment by Srijan205** [comment]
i want to work on this issue as a participant of GSSOC'21

**Comment by prisha-srivastava** [comment]
@PoojaMittal2842 
Due to some reason, I won't be able to work on this issue anymore. I hope somebody else can.

**Comment by ayu222220** [comment]
Can I work on this GSSOC'21. Can you assign me this

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Please assign this to me.
