### ISSUE TITLE
Use Css to make the page more attractive

### ISSUE THREAD

**Issue by SAHU-01** [PoojaMittal2842/Delhi-Tourism#42]
We can use alot of Css to make and change the homepage to a more attractive one with more disticnt divisions and a header and footer can also be added.

The registration can altogether be changed to a different part on the or link.

**Comment by IdealisticINTJ** [comment]
I would like to work on this. Please assign it to me. I am pretty proficient in HTML/CSS.

**Comment by sgpritam** [comment]
Duplicate issues
