### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [PoojaMittal2842/Delhi-Tourism#43]
I would like to add contributing.md file . I will contribute by putting steps on how to clone a repo and install on local system ,how to make a branch and use git commands to push it to origin ,How to make a PR , how to update your forked repo as well as local repo as the changes are made to the upstream

I would like to work on this as a part of GSSOC'21

**Comment by aditisneh** [comment]
Hey, as @khareyash05  is doing all stuffs regarding user guidelines on how to contribute, I would like to add a cool banner to the md and with neon effects. Basically I will be making the readme more attractive.
I would like to be assigned with this issue as a part of gssoc21. Kindly add gssoc21 tag to this as well. Thank You.

**Comment by gaurav24072002** [comment]
@khareyash05 I have already added contributing.md file so there is no need to make it but yes you can improve it. so go ahead 😄

**Comment by khareyash05** [comment]
Attached a PR @sgpritam Have a look

**Comment by khareyash05** [comment]
@sgpritam Could you pls also add a level label to the same
