### ISSUE TITLE
Login Page (Front end)

### ISSUE THREAD

**Issue by maverick1910** [PoojaMittal2842/Delhi-Tourism#82]
Create a Login page for the Delhi Tourism website. The page should be responsive and the tech stack given for the project should be used. Please send in a picture/video during PR's.

The details should be:
-Email 
-Password
-Login with Google
-Login with Facebook 

Anyone who is willing to work on this, please comment on this issue so I can assign them the task

**Comment by EANimesha** [comment]
Hi I am a Gssoc participant and I like to work on this issue.

**Comment by kanchi12P** [comment]
I am gssoc,21 participant, 
I would like to work on this issue

**Comment by abhishek96k** [comment]
I would like to work on this issue
as part of the `gssoc`

**Comment by maverick1910** [comment]
Hey @abhishek96k @kanchi12P , I have already assigned the login page to other participants , I'll create more issues which you guys can work on !

**Comment by EANimesha** [comment]
Thanks, @maverick1910 I am working on frontend design

**Comment by EANimesha** [comment]
@maverick1910 could you please add level label. otherwise, my contribution may not be counted for gssoc
