### ISSUE TITLE
Gallary Page(Front-end)

### ISSUE THREAD

**Issue by SAHU-01** [PoojaMittal2842/Delhi-Tourism#93]
I'd like to contribute by makeing a gallary.html where according to different categories the images will be shown.

**Comment by Ayushbajpai19** [comment]
I would like to contribute to this issue under GSSOC'21. So I can start working on it once you approve.

**Comment by neha030** [comment]
I am a GSSOC participant and want to work on the issue...
I can create a html file which will have different sections with various images.
please assign me this.

**Comment by Elizah550** [comment]
Heyy !!!
I can work on this with great difference please assign it to me.I have good experience in web development.
Thanks!!
