### ISSUE TITLE
adding home page

### ISSUE THREAD

**Issue by bitaashna** [PoojaMittal2842/Delhi-Tourism#99]
I would like to create a home page which will consist of navigation bar and routes to different pages by just clicking on it.
The home page will be having following features scrollling to the up of the page when bottom is reached
I will be using animations to make it more attractive
**I would like to contribute to it.
Can you please assign it to me under the label GSSOC'21**
@maverick1910

**Comment by Elizah550** [comment]
Heyy !!!
I am a web developer have great experience and I can work on this issue please assign it to me. My results will never make you unhappy.
Thanks !!!
